export const cohort2024Data = [
  {
    id: "1",
    name: "Agang K. Ditlhogo",
    business_name: "The Clicking Generation Pty Ltd",
    sector: "Technology",
    products: "Digital Skills Training",
    business_profile:
      "Agang K. Ditlhogo runs The Clicking Generation, offering digital skills training and consultancy services for businesses and individuals. Despite challenges during Covid-19, she continues operations in Maun with plans to expand. Her mission is to empower others in tech, with a focus on girls and women in STEM. Agang’s initiatives include coding, robotics, and corporate training programs, impacting over 20 schools and generating significant revenue last year.",
    avatar: "/img/cohorts/agang.png",
    website: "https://www.theclickinggeneration.org/ ",
  },
  {
    id: "2",
    name: "Atamelang Adelaide Samantha Free",
    business_name: "Skin Free Soaps",
    sector: "Skin Care",
    products: "Skin Care Products",
    business_profile:
      "Skin Free Soaps manufactures plant-based skincare products to promote mental wellness and self-confidence. The company takes a holistic approach, addressing mental well-being through its product line.",
    avatar: "/img/cohorts/atamelang.png",
    website: null,
  },
  {
    id: "3",
    name: "Betsi Maretlwaneng",
    business_name: "Mmale Investments",
    sector: "Hand Craft",
    products: "Jewelry",
    business_profile:
      "Mmale Investments specializes in beadwork and crafts, offering unique handcrafted jewelry.",
    avatar: "/img/cohorts/betsi.png",
    website: null,
  },
  {
    id: "4",
    name: "Dimpo Janet Lecha",
    business_name: "Psych Aide Pty (Ltd)",
    sector: "Health Care",
    products: "Science-Based Health Solutions",
    business_profile:
      "Psych Aide provides holistic, science-based psychological health and productivity solutions for individuals and businesses. Founded in response to post-Covid-19 workplace challenges, it bridges gaps between workers and organizational systems. The company aims to enhance well-being and productivity through tailored services.",
    avatar: "/img/cohorts/dimpo.png",
    website: null,
  },
  {
    id: "5",
    name: "Florence Tshiamo Koobake",
    business_name: "Aquasprings Still Water",
    sector: "Water",
    products: "Water Purification",
    business_profile: "N/A",
    avatar: "/img/cohorts/florence.png",
    website: null,
  },
  {
    id: "6",
    name: "Gadibusetse Setshwantsho",
    business_name: "Infinite Technologies",
    sector: "Technology",
    products: "Digital Products",
    business_profile:
      "Infinite Technologies creates innovative websites with user-centric designs that drive success.",
    avatar: "/img/cohorts/gadibusetse.png",
    website: "https://www.infinite.co.bw/ ",
  },
  {
    id: "7",
    name: "Heather Monare",
    business_name: "Hatherleigh Co.",
    sector: "Media",
    products: "Online Store",
    business_profile:
      "Hatherleigh Co. provides affordable branding and digital marketing services to SMEs, integrating AI to enhance efficiency. The company connects businesses with university interns, providing hands-on experience while delivering cost-effective solutions. AI-powered tools help clients strategize and execute campaigns effectively. Their subscription service offers small business owners industry-leading advice and insights.",
    avatar: "/img/cohorts/heather.png",
    website: null,
  },
  {
    id: "8",
    name: "Kealeboga Merafhe Siwawa",
    business_name: "Mahwatjitje Pty Ltd T/A Nthoppa",
    sector: "Fin Tech",
    products: "Digital Solutions",
    business_profile:
      "Nthoppa is a woman-led platform bridging gaps in financial services for underserved populations. It offers tailored financial tools, education, and a marketplace to support rural economic value chains. Aligned with national and continental visions for digital inclusion, the company leverages existing technologies to create affordable, accessible solutions.",
    avatar: "/img/cohorts/kealeboga.png",
    website: null,
  },
  {
    id: "9",
    name: "Keitumetse Ketlhoilwe",
    business_name: "Yummy Farms",
    sector: "Agricutlure",
    products: "Farm Produce",
    business_profile:
      "Yummy Farms specializes in organic farming, promoting sustainable agriculture.",
    avatar: "/img/cohorts/keitumetse.png",
    website: null,
  },
  {
    id: "10",
    name: "Lebogang G Solomon",
    business_name: "Lgs International",
    sector: "Technology",
    products: "Learning Mobile App",
    business_profile:
      "Lgs International developed Ikatise, a mobile app designed to help Botswana learners pass the Class B driving theory test. The app includes structured modules, simulated exams, progress tracking, and offline accessibility to ensure seamless learning.",
    avatar: "/img/cohorts/lebogang.png",
    website: null,
  },
  {
    id: "11",
    name: "Matlhogonolo Seadimo",
    business_name: "Mattie's Success (Pty) Ltd",
    sector: "Beauty",
    products: "Hair & Braid Manufacturing",
    business_profile:
      "Mattie's Success manufactures synthetic hair braids, with plans to innovate by recycling plastics into synthetic fiber. The company addresses a market gap by offering locally manufactured products and aims to expand its innovation in Africa. Benchmarking efforts in China are planned for 2025.",
    avatar: "/img/cohorts/matlhogonolo.png",
    website: null,
  },
  {
    id: "12",
    name: "Mboko Basiami",
    business_name: "Glotto",
    sector: "Clothing Brand",
    products: "Clothing",
    business_profile:
      "Glotto creates ready-to-wear, bespoke, and runway garments blending minimalistic silhouettes with bold textures. The brand harnesses digital platforms and analytics for marketing and distribution, building strong connections with its audience. Glotto’s transparent evolution enhances its brand identity and consumer trust.",
    avatar: "/img/cohorts/mboko.png",
    website: "https://glottobrand.com/",
  },
  {
    id: "13",
    name: "Mmakwena Moesi",
    business_name: "Viva Organica",
    sector: "Bio-Tech",
    products: "Provide Sustainable Input To Farmers",
    business_profile:
      "Viva Organica supports smallholder farmers with sustainable agricultural inputs, including biofertilizers and organic seeds, to improve soil health and crop yields. We are introducing eco-friendly biopesticides to reduce reliance on synthetic chemicals and developing AI-driven tools for early pest and disease detection. Our mission is to create a sustainable agricultural ecosystem that enhances food security and fosters resilience in local farming communities.",
    avatar: "/img/cohorts/mmakwena.png",
    website: null,
  },
  {
    id: "14",
    name: "Neo Bridgette Nthepha Kitso",
    business_name: "Tlhakakgolo Literary Journal",
    sector: "Media",
    products: "Online Store",
    business_profile:
      "Tlhakakgolo Literary Journal blends traditional narratives with modern technology through digital storytelling and AI-powered content curation. We host virtual writing workshops led by African creatives and partner with cultural institutions to preserve African heritage. Our sustainable publishing practices reflect our commitment to the environment and cultural preservation.",
    avatar: "/img/cohorts/neo.png",
    website: null,
  },
  {
    id: "15",
    name: "Ontifile Gaokgorwe",
    business_name: "The Bees Hive Academy",
    sector: "Education",
    products: "Education",
    business_profile:
      "The Bees Hive Academy offers inclusive early childhood education in Botswana with personalized learning programs. Our Inclusion Hub Connect platform provides remote assessments and resources for children with learning disabilities, fostering equal learning opportunities.",
    avatar: "/img/cohorts/ontifile.png",
    website: "https://thebeeshiveacademy.com/ ",
  },
  {
    id: "16",
    name: "Pelontle Maphula",
    business_name: "Solar World Botswana",
    sector: "Solar Energy",
    products: "Solar Systems",
    business_profile:
      "Solar World addresses energy challenges in Botswana with high-quality solar solutions and after-sales services. We integrate smart technology into farming and promote market education on solar benefits. Committed to renewable energy, we aim to expand across Southern Africa while supporting farmers with sustainable solutions.",
    avatar: "/img/cohorts/pelontle.png",
    website: "https://solarworldbotswana.co.bw/",
  },
  {
    id: "17",
    name: "Reitumetse Keikotlhaile",
    business_name: "Aenê Collective",
    sector: "Education",
    products: "Culture Agency",
    business_profile:
      "Aenê Collective is a Botswana-based agency providing indigenous language and cultural services, including language acquisition and translation. Our mission is to preserve and promote local languages and cultural heritage.",
    avatar: "/img/cohorts/reitumetse.png",
    website: null,
  },
  {
    id: "18",
    name: "Tebogo Kale",
    business_name: "T.B.K Potato Farm Pty (Ltd)",
    sector: "Agriculture",
    products: "Seedling Production",
    business_profile:
      "T.B.K Potato Farm uses technology like inventory and customer relationship management systems to optimize operations. With mentorship from experts, we aim to grow our business and deliver better services to our customers.",
    avatar: "/img/cohorts/tebogo.png",
    website: null,
  },
  {
    id: "19",
    name: "Thatayaone Nkokoto",
    business_name: "Migwom (Pty) Ltd",
    sector: "Machinery",
    products: "Industrial Automation",
    business_profile:
      "Migwom specializes in automating telemetry instruments and integrating cameras into SCADA systems, enhancing industrial automation solutions.",
    avatar: "/img/cohorts/thatayaone.png",
    website: null,
  },
  {
    id: "20",
    name: "Tlamelo Cindy Melemo",
    business_name: "Softberry Solutions",
    sector: "Technology",
    products: "Digital Products",
    business_profile:
      "Softberry Solutions provides digital products to bridge the technology divide in Africa. Our e-commerce platforms, such as Ko Dishopong and Sebaga Africa, enable intra-African trade and connect African products to global markets.",
    avatar: "/img/cohorts/tlamelo.png",
    website: null,
  },
];
